-- OGameX AI task DB — seed. The plan docs are the SOURCE OF TRUTH; this DB is the index agents
-- claim work from. Rebuild any time:  sqlite3 plan/tasks/tasks.db < plan/tasks/seed.sql
-- Status flow: todo -> in_progress -> done | blocked | deferred | open. Only 'todo' tasks appear in
-- ready_tasks once every dependency is 'done'.

PRAGMA foreign_keys = ON;

-- schema changes: drop and rebuild (re-seeding resets statuses, which is the documented behaviour)
DROP VIEW IF EXISTS ready_tasks;
DROP VIEW IF EXISTS blocked_tasks;
DROP TABLE IF EXISTS dependencies;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS meta;

CREATE TABLE IF NOT EXISTS meta (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
  id             INTEGER PRIMARY KEY,
  code           TEXT UNIQUE NOT NULL,
  title          TEXT NOT NULL,
  kind           TEXT NOT NULL CHECK (kind IN ('review','doc','impl','deferred','discovery')),
  status         TEXT NOT NULL DEFAULT 'todo'
                 CHECK (status IN ('todo','in_progress','blocked','done','deferred','open')),
  priority       TEXT CHECK (priority IN ('P0','P1','P2','P3')),
  assignee       TEXT,
  gap_ref        TEXT,            -- GAP-REGISTER id(s)
  principle_refs TEXT,            -- strategy-principles.md id(s)
  algorithm_ref  TEXT,            -- gameplay-algorithms.md block(s)
  doc_refs       TEXT,            -- docs that describe the work
  file_ref       TEXT,            -- primary file(s) to edit
  notes          TEXT,
  updated_at     TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS dependencies (
  task_id    INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  depends_on INTEGER NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  reason     TEXT,
  PRIMARY KEY (task_id, depends_on)
);

-- ready = todo and every dependency done
CREATE VIEW IF NOT EXISTS ready_tasks AS
SELECT t.*
FROM tasks t
WHERE t.status = 'todo'
  AND NOT EXISTS (
    SELECT 1 FROM dependencies d
    JOIN tasks dep ON dep.id = d.depends_on
    WHERE d.task_id = t.id AND dep.status <> 'done'
  );

CREATE VIEW IF NOT EXISTS blocked_tasks AS
SELECT t.*
FROM tasks t
WHERE t.status = 'todo'
  AND EXISTS (
    SELECT 1 FROM dependencies d
    JOIN tasks dep ON dep.id = d.depends_on
    WHERE d.task_id = t.id AND dep.status <> 'done'
  );

INSERT OR REPLACE INTO meta (key, value) VALUES
 ('schema_version', '1'),
 ('source_of_truth', 'plan/details/GAP-REGISTER.md, plan/details/research/strategy/README.md, plan/details/research/architecture-mapping.md, plan/details/specs/gameplay-algorithms.md'),
 ('updated', '2026-09-16');

-- ── tasks ────────────────────────────────────────────────────────────────────────────────────────────
INSERT OR REPLACE INTO tasks
 (id, code, title, kind, status, priority, gap_ref, principle_refs, algorithm_ref, doc_refs, file_ref, notes, updated_at) VALUES
 (1,'REV-001','Catalog review — pass the 10 integration gates','review','done','P0','W6-1..6',NULL,NULL,'specs/strategy-mining.md (Integration gates L)',NULL,'Owner sign-off. No implementation starts until the cluster passes all 10 gates; the last gate is `bash scripts/ogamex gate`.','2026-09-15 15:23:25'),
 (2,'IMPL-013','SP7 — the activity and intel reader','impl','done','P1','W6-1,W6-2,W6-3','RAID-004,RAID-005,RAID-006,INT-004,INT-005,INT-006,INT-010','SP7','specs/gameplay-algorithms.md (SP7); research/architecture-mapping.md','app/Domain/Decision/PlayerObservationService.php (targetReports)','One read-only reader: activity_at, moon_only_activity, intel_confidence, activity_probability_at_eta. Unblocks T6/T8/N4/V6.','2026-09-15 15:23:14'),
 (3,'IMPL-014','Raid depth — T6 target score, T7 tiered gate + cargo, T8 launch re-check','impl','done','P1','W6-1','RAID-004..014','T6,T7,T8','specs/gameplay-algorithms.md (T6-T8)','app/Domain/Decision/RaidPlanner.php; app/Domain/Decision/QueueAiRaidAction.php','Replace confidence=1.0 and travel_cost=0.0 placeholders; add activity risk, per-type intel decay, tiered profit gate, cargo sizing, dispatch re-check.','2026-09-15 15:45:46'),
 (4,'IMPL-015','Intelligence depth — N4 spy target score, N5 own signature','impl','done','P1','W6-2','INT-003,INT-007,INT-009,INT-011,INT-012','N4,N5','specs/gameplay-algorithms.md (N4-N5)','app/Domain/Decision/QueueableSpyPlanner.php','Replace id-order first-fit with a distance/novelty/yield score; dispatch and disappear.','2026-09-15 15:55:44'),
 (5,'IMPL-016','Save depth — V6 proactive save, V7 variation + masking, V8 shadow waves','impl','done','P1','W6-3','FS-001,FS-002,FS-005,FS-006,FS-008,FS-009,FS-011','V6,V7,V8','specs/gameplay-algorithms.md (V6-V8)','app/Domain/Decision/QueueableFleetSavePlanner.php','Proactive offline-gap trigger, route × speed scoring, dispatch masking, shadow waves.','2026-09-15 16:04:42'),
 (6,'IMPL-017','Fleetcrash — F1-F6 phalanx/recall/moon/recycle/lanx/moon-destruction','impl','done','P1','W6-5','CRASH-001..014','F1,F2,F3,F4,F5,F6','specs/gameplay-algorithms.md (F1-F6); research/architecture-mapping.md','new planners over PhalanxService/cancelMission/RecycleMission','Host-supported, zero module callers today. After 13-16; Pass-4 niche.','2026-09-15 16:50:32'),
 (7,'IMPL-018','Fleet composition — U-series production + launch subset, counters, recyclers','impl','done','P1','W6-4','FLE-002,FLE-004,FLE-012,FLE-013,FLE-014,FLE-015','U-series (block to write)','specs/gameplay-algorithms.md (U1-U4); research/strategy/principles/fleet-composition.yaml','app/Domain/Decision/QueueableUnitPlanner.php','Next increment: payload-sized cargo, stage composition, production-vs-launch split. Parallel-safe once reviewed.','2026-09-15 16:17:36'),
 (8,'IMPL-019','Ninja executor','impl','done','P2','pass-6 (new)','NIN-001..005','(new block)','research/architecture-mapping.md (pass-6)','new defence/reaction executor','No executor exists. Depends on fleet timing (IMPL-017). | blocked: NN2 ninja trap is gated behind a reviewed cluster per gameplay-algorithms.md (''advanced tactic gated behind a reviewed cluster, never silent''); NN1 phalanx staging check needs a moon+phalanx no account yet builds (F3 leaves moon-building open) and the activity fallback is already shipped as T8.','2026-09-15 17:30:23'),
 (9,'IMPL-020','Expedition executor','impl','done','P2','pass-6 (new)','EXP-001,EXP-002','(new block)','research/architecture-mapping.md (pass-6)','new expedition executor','Host expedition surface NOT re-verified — blocked on DISC-004.','2026-09-15 17:24:40'),
 (10,'DEF-001','V2 reaction wake','deferred','done','P2','G8','FS-004','V2','specs/gameplay-algorithms.md (V2)',NULL,'Deferred. Re-checked 16 Sep after the capacity runs: the wake-scheduling mechanism already exists (SessionDecisionService::scheduleSuccessor accepts an absolute next_due_at) and the inbound ETA is already observed (PerceptionSnapshot::inboundFleets[].time_arrival), so V2 no longer depends on full SP3. It stays deferred because the reaction-window semantics rework the shipped save-on-notice behaviour (V1): withhold when arrival > 180 s out, schedule a wake at arrival - draw(120,180), save inside the window, never save below the host 10 s detector floor - and that touches V3 (SaveFailurePolicy draw timing), V6 (proactive absence saves) and the dark-period wake logic. Needs a live inbound-fleet re-measure to calibrate the window boundary first. Narrow path: publish reaction_wake_at in inboundThreat(), clamp next_due_at in SessionDecisionService, re-base fleetsave tests on the window.','2026-09-16 19:11:25'),
 (11,'DEF-002','X1 transfer executor','deferred','done','P2','G17',NULL,'X1','specs/gameplay-algorithms.md (X1)',NULL,'Trigger decided; executor next slice.','2026-09-15 17:56:25'),
 (12,'DEF-003','Social / ACS / alliance life (Package 6)','deferred','deferred','P3','G12,G18,S1-S4','SOC-001,SOC-002,ACS-001..014','SOC1,SOC2','plan/WORK-PACKAGES.md (Package 6)',NULL,'Alliance-gated; deferred to Package 6.','2026-09-15 14:41:40'),
 (13,'DISC-001','Re-source ACS tutorials ORG-009/010','discovery','done','P3',NULL,NULL,NULL,'research/strategy/sources.yaml; research/source-registry.md',NULL,'Wayback failed; GF-003 suffices. Non-blocking. Closed 17 Sep 2026 by CDX enumeration + exact-URL replay (the 15 Sep failure was URL keying, not availability: the Wayback key includes the captured query string, so dropping ?s=<token> returns a 404 that reads as not archived). ORG-009 RECOVERED: Thread/618 (capture 2023-02-06, 37 KB) and Thread/790 (capture 2022-10-04, 83 KB) both replay with full ACS text - union attack flow, five-player cap, ACS defend deploy - an independent confirmation of the GF-003-sourced ACS-001..012 claims, so no re-mining. ORG-010 (Thread/621 colonisation) has NO capture at all and its domain is already sourced by TP-016/WIK-012/PLW-002, so it closes as unrecoverable. Registry + sources.yaml updated.','2026-09-17 12:37:03'),
 (14,'DISC-002','French board guide library','discovery','done','P3',NULL,NULL,NULL,'research/strategy/sources.yaml; research/source-registry.md',NULL,'Confirmed to exist; thread URLs not retrievable. Non-blocking. Closed 17 Sep 2026: the threads ARE archived and replay. Library is board.fr.ogame.gameforge.com board611-tutoriels-jeu-forum (under board1474-ogame-le-jeu/board103-support-et-questions/); the board thread form is /index.php?thread/<id>-<slug>/. Verified replays: 441237 Tutorial Raider Top player (316 KB, 2014-08-27) and 726448 Guide du Mineur (84 KB, 2020-12-05); 7 more threads listed in source-registry.md as retrievable-not-yet-mined. Two sources added to the canonical store as FRB-001/FRB-002 (priority C). The earlier not-retrievable reading came from the forum-root path.','2026-09-17 12:37:03'),
 (15,'DISC-003','ogamewiki.de','discovery','done','P3',NULL,NULL,NULL,'research/source-registry.md',NULL,'Extraction failed. Non-blocking. Closed 17 Sep 2026 as unrecoverable: ogamewiki.de, www.ogamewiki.de, ogame-wiki.de and ogamewiki.com all return NXDOMAIN, and the Wayback index holds ZERO captures for the domain, so there is nothing to retrieve - the site never existed in the archive. The German gap stays covered by DEW-001 (build formula, Fandom DE) and DEF-001 (German board FAQ thread). Recorded in source-registry.md; no sources.yaml row existed for it.','2026-09-17 12:37:03'),
 (16,'DISC-004','Verify expedition host surface','discovery','done','P2',NULL,'EXP-001,EXP-002',NULL,'research/host-capability-map.md',NULL,'Host expedition mission support unverified; blocks IMPL-020.','2026-09-15 16:55:28'),
 (17,'DOC-001','Write U-series fleet-composition algorithm blocks','doc','done','P1','W6-4','FLE-002,FLE-004,FLE-009,FLE-010,FLE-011,FLE-012,FLE-013,FLE-014,FLE-015','U-series (new)','specs/gameplay-algorithms.md (U1-U4); research/strategy/principles/fleet-composition.yaml','plan/details/specs/gameplay-algorithms.md','Production-vs-launch split, stage composition, counters, recycler sizing, payload-sized cargo. Documentation only; unblocks IMPL-018.','2026-09-15 14:53:17'),
 (18,'DOC-002','Write ninja algorithm block','doc','done','P2','pass-6 (new)','NIN-001..005','N-series (new)','research/strategy/principles/ninja-baiting.yaml; research/architecture-mapping.md (pass-6)','plan/details/specs/gameplay-algorithms.md','Defender counter-crash: staging, combat-second landing, bait, anti-ninja checks. Documentation only; unblocks IMPL-019.','2026-09-15 14:54:12'),
 (19,'DOC-003','Write expedition algorithm block','doc','done','P2','pass-6 (new)','EXP-001,EXP-002','E-series (new)','research/strategy/principles/expeditions.yaml','plan/details/specs/gameplay-algorithms.md','Slot-16 outcomes, never-fleetsave rule. Documentation only; host surface unverified; unblocks IMPL-020.','2026-09-15 14:55:09'),
 (20,'IMPL-021','SP5 — reservation before spending','impl','done','P2','W6','SP5','SP5',NULL,'app/Domain/Decision/QueueableBuildingPlanner.php','Per-resource floor that survives a build/research purchase, reduced by production over the saving horizon. keep_resources_buffer 0.10, max_saving_hours_economy 4.0, max_saving_hours_research 6.0. Unblocks DEF-002 X1.','2026-09-15 17:44:38'),
 (21,'DOC-004','Close T6/V7 residuals — mark clustering + route×speed shipped, defer relationship/contest','doc','done','P2','W6-1,W6-3',NULL,'T6,V7',NULL,'plan/details/specs/gameplay-algorithms.md','Doc-only accuracy pass: proximity clustering is already shipped via travel_cost (pinned by ''owned state prices a distant target higher than a near one''); V7 route x speed is resolved for deployment saves (slowest speed is fuel-minimal, destination ranking shipped). Record relationship (RAID-007) and contest (RAID-013) as deferred with precise reasons.','2026-09-15 19:23:30'),
 (22,'IMPL-022','Capability research — queue a leaf research that unlocks a non-object capability (astrophysics)','impl','done','P1','G2,G7,G3','R2','R2',NULL,'app/Domain/Decision/FacilityChain.php','Live grand run (15 Sep): all 10 accounts have astro=0 after 8h at 1000x, and 7 of them meet every astrophysics prerequisite (research_lab>=3, espionage>=4, impulse>=3). Consequence: colonize and expedition never fire. Root cause: FacilityChain is the only research source; ambitions() = research+unit objects sorted cheapest-first, and pending() returns only the UNMET PREREQUISITES of the cheapest non-producible ambition. nextAmbition() skips an ambition whose prerequisites all stand, so a leaf research that no unit requires (astrophysics) is never queued. Its prerequisites get climbed, then it is skipped forever. R2 says such a research must score through the capability it unlocks.','2026-09-15 20:41:18'),
 (23,'IMPL-023','Close the module PCOV coverage gaps (98.79% -> 100%)','impl','done','P1','W6-1,W6-3',NULL,NULL,NULL,NULL,'coverage gate red: 5780/5851 = 98.79%, exit 1. Gaps: ExecuteAiIntentAction 207-238 (the transfer() arm), QueueAiTransferAction 40,43,50,53,77,78,92,98,103, ScheduleAiIntentAction 260-267 (scheduleTransfer), CandidateActionFactory 139-145 (eligibleTransferCandidates) + 196-202 (raid candidate creation), QueueableFleetSavePlanner 63,119, QueueableTransferPlanner 73,96,123,153,173, RaidPlanner 82 (storageReady capacity<=0), UtilityScorer 36 (policy-denied continue), PlayerObservationService 148, AiCandidateReason 21,23 (reportSource), ProcessAiWork 281 (no schedule row), AIServiceProvider 139 (10s session interval). app/Rules is excluded from the gate. NOTE: parallel workers isolate test files, so shared helpers must be require_once''d from tests/Pest.php as a Support file/class (the FixturePlayerPerceptionBuilder pattern); helpers defined in a test file are NOT visible to another test file, and cross-file use passes serial (coverage) but fails parallel (test).','2026-09-15 21:45:43'),
 (24,'DOC-005','Flip the strategy source to YAML and extract the atomic-claims layer','doc','done','P2',NULL,NULL,'strategy',NULL,'plan/details/research/strategy/README.md','Follow-up to the Strategy Knowledge Storage Format. (a) Flip the source: make the YAML canonical and regenerate/repoint the Markdown consumers (gameplay-algorithms.md, GAP-REGISTER.md, task DB doc_refs) so there is one authority. (b) Extract the atomic claims layer (claims/*.yaml) from the sources — the repo currently goes sources -> principles with only a classification (now claim_type on each principle).','2026-09-16 16:12:12'),
 (25,'IMPL-024','Spend a windfall before warehousing it (W7-1/W7-2)','impl','done','P2','W7-1,W7-2',NULL,'E6',NULL,'plan/details/specs/gameplay-algorithms.md','planned; smallest slice undecided — two hypotheses in E6, needs a frozen-clock before/after','2026-09-16 11:24:16'),
 (26,'IMPL-025','Scarcity-weighted resource need: the scarce resource ranks above the persona habit','impl','done','P2','W7-1',NULL,'E6',NULL,'app/Domain/Decision/CandidateActionFactory.php','The other half of W7-1: a fleeter ranks ships 15 points above mines in every session. Give Build a scarcity-weighted resource_need so it wins exactly when a resource is the binding constraint; frozen-clock before/after.','2026-09-16 12:37:20'),
 (27,'IMPL-026','Objective resolution from a committed coalition victory','impl','done','P2',NULL,NULL,NULL,'specs/pve-empire.md','app/Actions/ResolveAiCampaignObjectiveFromBattleReportAction.php; app/Observers/ObserveCommittedBattleReport.php; app/Models/AiCampaignObjective.php','A committed battle report whose attacker wins against a declared objective planet marks that objective complete once. A draw, retreat or defender win does not count; winning does not capture the planet.','2026-09-16 13:16:10'),
 (28,'IMPL-027','Campaign director lifecycle','impl','done','P2',NULL,NULL,NULL,'specs/pve-empire.md','app/Actions/AdvanceAiCampaignStateAction.php; app/Models/AiCampaign.php','Preparing->Active at starts_at; Active->Resolved when every declared objective completes on time; Failed when the deadline passes with an incomplete set. Idempotent terminal states.','2026-09-16 13:16:10'),
 (29,'IMPL-028','Reward allocator','impl','done','P2',NULL,NULL,NULL,'specs/pve-empire.md',NULL,'Ordinary loot/debris plus campaign recognition; cap repeated contribution credit and exclude AI participation from human credit.','2026-09-16 13:16:10'),
 (30,'DEF-004','Cooperative hostility extension point (E6/E7) + module policy registration','impl','done','P3',NULL,NULL,NULL,'specs/module-extension-points.md (E6/E7); specs/pve-empire.md','app/Contracts/HostilityPolicy.php; app/Services/HostilityGuard.php; Modules/AI/app/Support/CooperativeHostilityPolicy.php','Host pull request for the HostilityPolicy + registry must land first; the module side is registration only.','2026-09-16 13:00:35'),
 (31,'IMPL-029','6C — operator control and fail-closed LLM admission','impl','done','P2',NULL,NULL,NULL,'WORK-PACKAGES.md (6C); specs/pve-empire.md',NULL,'Off/observe/advice modes, enablement, kill switch, provider ladder, trigger cooldowns, advice age, evidence-inclusion policy and hard token/attempt/cost/concurrency caps. Off resolves no Laravel AI config and contacts no provider; receipts never retain raw prompts. | blocked: LLM/provider phase — awaits owner green light after the deterministic baseline is verified','2026-09-16 13:54:18'),
 (32,'IMPL-030','6A — consultation transport + typed recommendation core','impl','done','P2',NULL,NULL,NULL,'WORK-PACKAGES.md (6A); specs/pve-empire.md',NULL,'Shipped: the structured-output agent, the Null/Laravel AI gateways, the request/recommendation domain, the fail-closed admission wiring and the candidate-membership validator. Remaining 6A (brief builder, receipt+budget+caps, ranking adjustment) are IMPL-032/033/034.','2026-09-16 13:58:23'),
 (33,'IMPL-031','6B — driver-signal utilisation for cooperative player divergence','impl','done','P3',NULL,NULL,NULL,'WORK-PACKAGES.md (6B); specs/pve-empire.md',NULL,'One bounded driver-evidence contribution at existing campaign decision points; profile traits decide reaction weight. Requires the 2/5/10 comparison showing a player-visible gain before any default. | blocked: measurement-gated — needs the 2/5/10 capacity-run comparison before it ships','2026-09-16 17:45:49'),
 (34,'IMPL-032','6A — bounded redacted advice brief builder','impl','done','P2',NULL,NULL,NULL,NULL,NULL,'Build the serialized redacted brief from current permitted campaign facts, legal executable candidates with native scores, and typed attributed driver evidence. Missing/invalid/stale/unauthorised driver evidence is absent.','2026-09-16 15:35:37'),
 (35,'IMPL-033','6A — consultation receipt, budget reservation and caps','impl','done','P2',NULL,NULL,NULL,NULL,NULL,'Persist a receipt per consultation (trigger, config revision, evidence IDs, provider/model, usage, validation result, changed ranking; never raw prompts or private facts). Reserve/settle usage through the existing budget; enforce daily ceilings, per-trigger cooldown and concurrency; uncertain usage settles once.','2026-09-16 15:35:37'),
 (36,'IMPL-034','6A — profile-bounded ranking adjustment','impl','done','P2',NULL,NULL,NULL,NULL,NULL,'Apply a validated recommendation as a profile-bounded adjustment to a later ranking; native policy still chooses and dispatches. No driver can promote an unavailable action or override a native refusal.','2026-09-16 15:35:37'),
 (37,'REV-002','Verify and pair-commit the Package 6 batch (module wip + host hostility half)','review','done','P0','W8-V1',NULL,NULL,'plan/WORK-PACKAGES.md (Package 6); plan/details/GAP-REGISTER.md (Wave 8)','app/ (the whole batch, commit bf064ac); host app/Services/HostilityGuard.php, app/Enums/UniverseMode.php, app/GameMissions/Abstracts/GameMission.php','The Package 6 slices landed as one commit named wip (bf064ac, 100 files) and the host half of the same pair is uncommitted, so the module registers CooperativeHostilityPolicy against host classes a fresh host checkout does not have. Run the module gates on bf064ac (Gate 2 review, Pint, PHPStan, Rector dry-run, Pest, PCOV), commit the host pair, then name each shipped slice in the record. Nothing measured on the running containers is evidence about a commit until this holds.','2026-09-16 18:48:34'),
 (38,'DOC-006','Wave-8 algorithm blocks: dispatch ceiling, full-storage spend, colonise eligibility, probe budget, quiet-decision reason','doc','done','P1','W8-L1,W8-L4,W8-L5,W7-3,W8-L7',NULL,'(new blocks)','plan/details/specs/gameplay-algorithms.md (gap index)','plan/details/specs/gameplay-algorithms.md','Name each algorithm with its host inputs, constants and their source, failure behaviour and acceptance before the code lands: the dispatch ceiling (host fleet-slot answer + host obligation R11), the full-storage spend precedence (E3/E6), colonise eligibility, the probe budget (INT-*), the quiet-decision stop reason. Documentation only; unblocks IMPL-035, IMPL-036, IMPL-037, IMPL-038 and IMPL-040.','2026-09-16 17:06:42'),
 (39,'IMPL-035','Host dispatch ceiling before publishing a dispatch (W8-L1)','impl','done','P1','W8-L1',NULL,'DS1 (new)','plan/details/GAP-REGISTER.md (Wave 8); plan/details/specs/gameplay-algorithms.md (DS1)','app/Domain/Decision/CandidateActionFactory.php; app/Domain/Decision/QueueableFleetSavePlanner.php','Only the save planner reads getFleetSlotsMax(), so colony, spy, raid, expedition and transfer dispatches are published and refused: 1027 receipts in 24 h, 917 CreateColony, all "Maximum number of fleets reached"; 8 of 10 accounts hold one slot because the object that raises the ceiling is never researched. Read the host ceiling (getFleetSlotsMax minus getFleetSlotsInUse) before publishing a dispatch, and let the build order reach the object that raises it. The host answer names computer_technology internally and ObjectService exposes no lookup by calculation type, so the reachability half needs the host obligation R11 (publish the object carrying MAX_FLEET_SLOTS) rather than a module-side object list.','2026-09-16 17:13:37'),
 (40,'IMPL-036','A planet at 100% storage must still spend (W8-L4)','impl','done','P1','W8-L4',NULL,'E6 (extend)','plan/details/GAP-REGISTER.md (Wave 8); plan/details/specs/gameplay-algorithms.md (E6)','app/Domain/Decision/EconomyUpgrades.php; app/Domain/Decision/QueueableBuildingPlanner.php; app/Domain/Decision/CandidateActionFactory.php','Four homeworlds sit at exactly 100% storage and are refused a warehouse (storage() skips hours <= 0.0 by design) while production() is bounded by the payback horizon, so 8.9M metal/h is discarded and QueueableBuildingPlanner::plan(20) returns research. Decide the E3/E6 precedence - an already-full warehouse is a spend signal - and measure the before/after on a frozen clock. W7-2 is recorded closed by IMPL-024 while the mid-day read re-measured the same collision, so re-check the closure first.','2026-09-16 17:16:34'),
 (41,'IMPL-037','Colonise must not outrank developing what the account owns (W8-L5)','impl','done','P1','W8-L5',NULL,'G7 (extend)','plan/details/GAP-REGISTER.md (Wave 8); plan/details/specs/gameplay-algorithms.md (G7)','app/Domain/Decision/CandidateActionFactory.php; app/Domain/Decision/QueueableColonyPlanner.php','p20 froze for 14 h: 174 sessions, 175 colonise candidates, 168 colonise work items, zero other decisions, 112 refused at the fleet cap, score +0 (rank 6 -> 10), and both of its colonies have production 0. Colonise scores ~49.6 against research 39.6 / units 40.1 / expedition 38.7, so a new body outranks the one that pays for it. Eligibility reads the host ceiling (IMPL-035) and whether the account can develop the body it would found. The un-materialised colony stats are DISC-005.','2026-09-16 17:19:25'),
 (42,'DISC-005','Two settled colonies have never materialised their stats (W8-L5)','discovery','done','P1','W8-L5',NULL,NULL,'plan/details/research/host-capability-map.md',NULL,'Resolved 16 Sep: the host materialises a settled colony. ColonisationMission::processArrival -> PlanetServiceFactory::createAdditionalPlanetForPlayer -> createPlanet writes metal=500, crystal=500, field_max, temperature, 100% mine percents and time_last_update=now, then fires PlanetCreated; QueueAiColonyAction goes through the host FleetMissionService path and skips no step. The observed zeros are the host lazy stat columns: metalStorage() reads planet.metal_max, which only PlanetService::update() (updateResourceStorageStats / updateResourceProductionStats) computes, and PlayerGameStateService::advance() updates only the current planet. RunAiSessionAction advances only the current planet, so a colony the account never visits keeps metal_max=0, production 0, no mines and its creation-time stamp; the stored 500/500 metal/crystal are present. No host defect and no skipped step - the account simply never develops its own new colony, the root IMPL-037 now guards at decision time. Non-blocking follow-up: the session loop never updates a non-current planet.','2026-09-16 18:58:45'),
 (43,'IMPL-038','The probe budget counts in-flight spy intents (W7-3)','impl','done','P2','W7-3',NULL,'INT-*','plan/details/specs/gameplay-algorithms.md (INT-*)','app/Domain/Decision/QueueableSpyPlanner.php','inFlightCoordinates() de-duplicates by target coordinates, so two scheduled probes for different targets both plan from one probe; 32 receipts were refused with "Not enough units on the planet to send the fleet. Units required: espionage_probe". The budget is idle probes minus probes already committed to a pending spy item.','2026-09-16 17:20:49'),
 (44,'DISC-006','Why the espionage-report flow and the raid pipeline starved (W8-L2)','discovery','done','P2','W8-L2',NULL,NULL,'plan/details/reviews/2026-09-16-grand-live-play-read.md',NULL,'Resolved 16 Sep: W8-L1 confirmed as the cause by code-read. An espionage mission is a fleet mission consuming one slot, and only its arrival creates EspionageReport (processArrival -> createEspionageReport); with 8/10 accounts holding one slot every probe dispatch was refused ("Maximum number of fleets reached") -> no missions flew -> no reports -> RaidPlanner had no fresh report -> Raid stopped being offered. IMPL-035 closes it two ways (candidate factory withholds spy/raid/colony/expedition/transfer when fleet_slots_free<1; FacilityChain reaches the ceiling object via the host R11 getObjectByCalculationType(MAX_FLEET_SLOTS)); IMPL-038 closes the secondary defect (probe budget counts pending spy intents). A live recovery re-measure belongs to the next capacity/pilot run, not code.','2026-09-16 18:58:45'),
 (45,'IMPL-040','The quiet decision writes a stop reason (W8-L7)','impl','done','P2','W8-L7',NULL,NULL,'plan/details/GAP-REGISTER.md (Wave 8); plan/details/specs/improvement-loop.md','app/Enums/AiStopReason.php; app/Actions/RecordAiStopReasonAction.php; the session path that ends in DoNothing','ai_stop_counters is empty after 31 h while 470 sessions chose DoNothing and every trace carries exactly one candidate whose reason is always_available, so no artifact says why nothing else was available - the same gap that leaves "why was FleetSave offered twice and Recall never" unanswerable. Record the reason where the quiet decision is already taken, only for mechanisms that already exist; no new table.','2026-09-16 17:22:03'),
 (46,'IMPL-041','The hourly score sample keeps a readable trail (W8-L6)','impl','done','P3','W8-L6',NULL,NULL,'plan/details/GAP-REGISTER.md (Wave 8); plan/details/specs/improvement-loop.md','app/Providers/AIServiceProvider.php (hourly entry); docker/entrypoint.sh (scheduler role)','ai_score_samples has no row between 15 Sep 22:00 and 16 Sep 12:00. The run log survives and is the evidence: the grand scheduler container (created 15 Sep 06:50) logs ai:record-score-samples five times, 15 Sep 07:00-11:00, and never again, while ai:run-due-work fires continuously, with no skipped or mutex line. Find why the entry stopped firing (entry guard, mutex, or a deploy) before adding any mechanism, then keep one bounded line per run.','2026-09-16 17:24:22'),
 (47,'REV-003','Re-measure the wave-8 rows on the committed build','review','done','P1','W8-V2,W8-L1,W8-L3,W8-L4,W8-L5',NULL,NULL,'plan/details/reviews/2026-09-16-grand-live-play-read.md; plan/details/GAP-REGISTER.md (Wave 8)',NULL,'The read ran the containers, which mount the working tree, and four rows are decision-core claims that IMPL-024 and IMPL-025 were written to change. Re-read each row against the committed build, with a frozen clock where the row asks for a before/after (L3 fleeter play, L4 storage precedence, L5 colonise), and correct or close it; a row measured while a live pilot writes is not evidence about the code.','2026-09-16 18:50:53'),
 (48,'REV-004','Run the 2/5/10 capacity comparison and record the figures (completion-gate item 1)','review','done','P1',NULL,NULL,NULL,'plan/WORK-PACKAGES.md (completion gate item 1); local-dev-docker capacity-run.sh','local-docker-dev/capacity-run.sh; plan/details/specs/budgets.md','Owner-rescaled from 100/500/1,000 to 2/5/10 accounts. Record per-profile campaign action, social and recovery divergence, latency, RAM, provider attempts and fallback rate against the native-only baseline. This is the gate IMPL-031 (6B) and DEF-001 (V2 reaction wake) wait on.','2026-09-16 17:25:20'),
 (49,'IMPL-042','SP3 next-material-event wake (W6-6)','impl','done','P2','W6-6','AUTH-004','SP3',NULL,'app/Domain/Scheduling/NextDueTimeCalculator.php; app/Domain/Scheduling/SessionDecisionService.php','SP3: next_wake = min(resource_eta, building_finish, research_finish, fleet_arrival, fleet_return, slot_free, storage_threshold) inside the waking window, plus the routine session as upper bound. W6-6 records SP3 as partial; V2 (DEF-001) shipped the hostile-inbound term. Close the remaining terms from host queue data (BuildingQueue/ResearchQueue time_end, fleet time_arrival) and the account''s production/storage fill.','2026-09-16 19:40:58'),
 (50,'LLM-002','S2 — bot and strategy research distilled for LLM prompts','doc','done','P1',NULL,NULL,NULL,NULL,'plan/details/research/llm-prompt-knowledge.md','Distill ogame-automation-algorithms.md (P1-P13), strategy-principles.md, veteran-play.md into a prompt-safe knowledge file. Gate 1: reasoning only, never object ids/machine names/prices.','2026-09-16 20:55:23'),
 (51,'LLM-006','S6 — priced model matrix + LLM feasibility and reporting','impl','done','P1',NULL,NULL,NULL,NULL,'config/pricing.php; app/Actions/ResolveAiUsageCostAction.php; app/Actions/SettleAiUsageReservationAction.php; app/Actions/BuildAiPilotReportAction.php; app/Actions/SummarizeAiOperabilityAction.php','Config provider.model -> input/cached/output per 1M with peak/off-peak; cost resolver fail-closed; record cost at settlement; report settled dollar cost.','2026-09-16 21:05:12'),
 (52,'LLM-001','S1 — prompt review + token-lean context','impl','done','P1',NULL,NULL,NULL,NULL,'app/Ai/Agents/OgameConversationReplyAgent.php; app/Ai/Agents/OgameCampaignConsultationAgent.php; app/Actions/GenerateAiReplyAction.php; app/Actions/BuildCampaignConsultationBriefAction.php','Cut prompt tokens to exactly what the model needs; allowlist schema; no object lists in prompts.','2026-09-16 21:06:50'),
 (53,'LLM-003','S3 — enable LLM by default + verified model names','impl','done','P1',NULL,NULL,NULL,NULL,'config/language.php; config/routing.php; app/Actions/ResolveAiProviderRouteAction.php','ai.language.enabled=true default; deepseek-flash default + gpt-5.6-luna fallback; replace gpt-5-mini.','2026-09-16 21:09:04'),
 (54,'LLM-005','S5 — thinking-model routing + escalation cascade','impl','done','P2',NULL,NULL,NULL,NULL,'app/Ai/Agents/OgameCampaignConsultationAgent.php; app/Actions/ResolveAiProviderRouteAction.php; config/routing.php','Per-task model route: reply->deepseek-flash, consultation->deepseek-v4-pro with thinking via HasProviderOptions; bounded one-step cascade.','2026-09-16 21:10:41'),
 (55,'LLM-004','S4 — wire the campaign consultation lane into its callers','impl','done','P1',NULL,NULL,NULL,NULL,'app/Actions/AdvanceAiCampaignStateAction.php; app/Actions/ResolveAiCampaignObjectiveFromBattleReportAction.php; app/Domain/Decision/CandidateActionFactory.php','Add the six AiCampaignConsultationTrigger sites; call RequestCampaignConsultationAction + ApplyCampaignConsultationRankingAction; observe/advice honored.','2026-09-16 21:17:15'),
 (56,'LLM-007','S7 — real-response Http::fake fixtures','impl','done','P2',NULL,NULL,NULL,NULL,'tests/Fixtures/llm/*.json; tests/Feature/*','Record real provider responses as JSON fixtures; Http::fake replay; keep SDK agent fake + preventStrayPrompts.','2026-09-16 21:12:57'),
 (57,'LLM-008','S4b — the remaining four campaign consultation triggers (fleet loss, rank change, repeated setback, coalition conflict)','impl','done','P2',NULL,NULL,NULL,NULL,NULL,'NewPhase + ContestedObjective are wired. These four need signals that do not exist yet: fleet loss needs side-loss detection on BattleReport, rank change needs per-campaign rank semantics over AiScoreSample, repeated setback needs a failed-battle counter, coalition conflict needs faction membership in the battle observer.','2026-09-16 21:46:58'),
 (58,'LLM-009','S8 — read-only tool set replacing prompt-stuffing (campaign consultation first)','impl','done','P2',NULL,NULL,NULL,NULL,NULL,'Build CampaignFactsTool, LegalCandidatesTool, CounterpartyFactsTool, HostCapabilityTool (Laravel\AI\Contracts\Tool); the consultation agent implements HasTools; base prompt shrinks to instructions + current turn; tools are host-read, bounded, read-only, never an authority. Studied in plan/details/research/laravel-ai-tools.md. DeepSeek + OpenAI support tool calls.','2026-09-16 21:55:07'),
 (59,'DISC-007','Source pass on hammermaps/OGameX-AI-Players (agent.md + AI-player controller)','discovery','done','P3',NULL,NULL,NULL,NULL,NULL,'Same-engine (lanedirt/OGameX) fork with 6 AI strategy profiles + daemon + admin UI. Record its profile taxonomy, scheduling and scoring against ours; find gaps, never port. Discovered 17 Sep in plan/details/research/ogame-ai-agents.md.','2026-09-16 21:58:54'),
 (60,'WP-001','Debris-field recycling loop','impl','done','P1',NULL,NULL,NULL,'plan/details/research/repos/WORK-PACKAGE.md','app/Domain/Decision/QueueableRecyclePlanner.php; app/Actions/QueueAiRecycleAction.php; app/Contracts/QueueAiRecycle.php; app/Enums/AiCandidateActionType.php; app/Enums/AiWorkKind.php; app/Domain/Decision/CandidateActionFactory.php; app/Providers/AIServiceProvider.php','New planner scans neighbourhood host DebrisField rows above a module loot threshold and dispatches recyclers via host RecycleMission; also harvests slot-16 debris an own expedition leaves. Skips fields already covered by an in-flight recycle. Host-read recycler/pathfinder classification via ObjectService (gate 1). Sources: jaesivsm-pyogame, janeczkins-xbot, kweimann-cruiser, ogame-ninja-scripts, r4fek-ogame-bot, trilogi77-ogamebot.','2026-09-17 12:44:27'),
 (61,'WP-002','Raid estimate — P20 loot quantile, delete expectedLoot()','impl','done','P1',NULL,NULL,NULL,'plan/details/research/repos/WORK-PACKAGE.md','app/Domain/Raid/RaidEstimate.php; app/Infrastructure/Battle/NativeRaidEstimator.php; app/Domain/Decision/RaidPlanner.php','Carry the host engine''s authoritative P20 loot (cargo-constrained, fill-ordered) out of the existing 50-run stream into clearsLootTier(); delete the hand-rolled min(metalEq x fraction, cargo) scalar so host fill order is the single loot authority. Sources: jstar88-opbe, klaasvp-trashsim.','2026-09-17 12:44:27'),
 (62,'WP-003','Raid estimate — survival floor (win/loss/draw + fleet-loss rate)','impl','done','P1',NULL,NULL,NULL,'plan/details/research/repos/WORK-PACKAGE.md','app/Domain/Raid/RaidEstimate.php; app/Infrastructure/Battle/NativeRaidEstimator.php; app/Domain/Decision/RaidPlanner.php','Read attackerUnitsResult/defenderUnitsResult per sampled run; carry pWin (survived) and a fleet-loss rate next to p20NetProfit/losingRuns; RaidPlanner refuses above a persona threshold so a coin-flip that profits never flies. Sources: maximalcode-combat-sim, klaasvp-trashsim, peterradzisz-fleet-optimizer.','2026-09-17 12:44:27'),
 (63,'WP-004','Fleetsave destination safety','impl','done','P1',NULL,NULL,NULL,'plan/details/research/repos/WORK-PACKAGE.md','app/Domain/Decision/QueueableFleetSavePlanner.php; app/Domain/Perception/PlayerObservationService.php','Exclude own bodies whose planet_id appears in the inbound picture before the moon/distance sort; prefer a same-coordinate planet-moon (distance-5) jump the phalanx cannot observe. Sources: halfguru-ogamebot, kweimann-cruiser.','2026-09-17 12:44:27'),
 (64,'WP-005','Single-planet fleetsave fallback (harvest-save)','impl','done','P1',NULL,NULL,NULL,'plan/details/research/repos/WORK-PACKAGE.md','app/Domain/Decision/QueueableFleetSavePlanner.php; app/Actions/QueueAiFleetSaveAction.php','When no second own body / no moon exists, save to a debris field with recyclers on a harvest mission instead of doing nothing. Source: ogame-tbot-tbot.','2026-09-17 12:44:27'),
 (65,'WP-006','Weak-attack / nothing-to-save fleetsave gate','impl','done','P1',NULL,NULL,NULL,'plan/details/research/repos/WORK-PACKAGE.md','app/Domain/Decision/QueueableFleetSavePlanner.php; app/Domain/Decision/SaveFailurePolicy.php; app/Domain/Perception/PlayerObservationService.php','Skip the reactive save when the local fleet is below the persona exposure band or the inbound is a probe-only / trivial fraction of the parked fleet; reuse the band proactivePlan() already applies, no new constant. Sources: ogame-tbot-tbot, janeczkins-xbot.','2026-09-17 12:44:27'),
 (66,'WP-007','Storage-before-build preprocessor','impl','done','P1',NULL,NULL,NULL,'plan/details/research/repos/WORK-PACKAGE.md','app/Domain/Decision/EconomyUpgrades.php; app/Domain/Decision/QueueableBuildingPlanner.php','When a build price exceeds the planet current storage, prepend the cheapest storage upgrade for the blocking resource before queueing the build. Source: racinmat-phpogamebot.','2026-09-17 12:44:27'),
 (67,'WP-008','Standing defence pass','impl','done','P2',NULL,NULL,NULL,'plan/details/research/repos/WORK-PACKAGE.md','app/Domain/Decision/QueueableUnitPlanner.php; app/Domain/Decision/Policies/TurtlePolicy.php','Turtle/miner personas keep a baseline defence at a persona-scaled ratio of fleet value (host-read getDefenseObjects()), not only reactively under underAttack. Sources: ogame-ninja-scripts, piecepapercode-barakis, trilogi77-ogamebot.','2026-09-17 12:44:27'),
 (68,'WP-009','Expedition fleet composition + system rotation','impl','done','P2',NULL,NULL,NULL,'plan/details/research/repos/WORK-PACKAGE.md','app/Domain/Decision/QueueableExpeditionPlanner.php; app/Domain/Decision/QueueableExpedition.php; app/Actions/QueueAiExpeditionAction.php','Dispatch a real expedition fleet — strongest combat hull (host attack), fastest civil hull as pathfinder (host speed), smallest cargo, a probe — and rotate the origin system after N outgoing expeditions. Sources: ogame-infinity-web-extension, trilogi77-ogamebot.','2026-09-17 12:49:29'),
 (69,'WP-010','Colony slot scoring (+ abandon)','impl','done','P2',NULL,NULL,NULL,'plan/details/research/repos/WORK-PACKAGE.md','app/Domain/Decision/QueueableColonyPlanner.php','Rank empty slots by host-reported fields and temperature (mid/large first, seeded walk), not the first empty slot; abandon-and-recolonise a below-band colony only once the host abandon seam is verified. Sources: halfguru-ogamebot, trilogi77-ogamebot, janeczkins-xbot.','2026-09-17 12:55:37'),
 (70,'WP-011','Recall scheduling at half-duration / absence-aware save speed','impl','done','P2',NULL,NULL,NULL,'plan/details/research/repos/WORK-PACKAGE.md','app/Domain/Decision/QueueableFleetSavePlanner.php; app/Actions/ScheduleAiIntentAction.php','Schedule the recall at ~half the deployment duration (per-account jitter) instead of an arbitrary later session; pick a save speed whose flight lands >= the upcoming absence. Sources: ogame-tbot-tbot, trilogi77-ogamebot.','2026-09-17 13:04:30'),
 (71,'WP-012','Surplus consolidation transfer','impl','done','P2',NULL,NULL,NULL,'plan/details/research/repos/WORK-PACKAGE.md','app/Domain/Decision/QueueableTransferPlanner.php; app/Domain/Decision/ReserveFloor.php','When a planet nears its storage cap, sweep the above-floor surplus to the best-developed body (keep a deuterium floor on moons), the reverse direction of the need-driven ferry. Sources: janeczkins-xbot, ogame-ninja-scripts.','2026-09-17 13:13:13'),
 (72,'WP-013','Defenceless-target intel signal + confidence downgrade','impl','done','P2',NULL,NULL,NULL,'plan/details/research/repos/WORK-PACKAGE.md','app/Domain/Perception/PlayerObservationService.php; app/Domain/Perception/ActivityIntelReader.php; app/Domain/Decision/RaidPlanner.php','Flag a report whose fleet and defence sections are present-and-empty ([] vs null) as defenceless so the raid gate can short-circuit the estimator; downgrade published confidence when sections are missing, never raise on null. Source: alaingilbert-ogame.','2026-09-17 13:22:55'),
 (73,'WP-014','Probe escalation + closest spy origin','impl','done','P2',NULL,NULL,NULL,'plan/details/research/repos/WORK-PACKAGE.md','app/Domain/Decision/QueueableSpyPlanner.php; app/Domain/Decision/QueueableSpy.php; app/Actions/QueueAiSpyAction.php','Escalate probe count (bounded 1-5) for defended/known-rich targets whose last report is partial; pick the closest own planet with an idle probe, not the first in collection order. Sources: racinmat-phpogamebot, ogame-tbot-tbot.','2026-09-17 13:35:31'),
 (74,'WP-015','Raid outcome feedback (cooldown + blacklist + real-loot attribution)','impl','done','P2',NULL,NULL,NULL,'plan/details/research/repos/WORK-PACKAGE.md','app/Domain/Decision/RaidPlanner.php; app/Actions/ExecuteAiIntentAction.php; app/Domain/Experience/','Skip a target hit within a cooldown window and blacklist one that underperformed across >=3 real raids; record post-raid loot through the experience rules so the P20 screen is re-weighted by what actually landed. Source: trilogi77-ogamebot.','2026-09-17 13:47:12'),
 (75,'WP-016','Message a new attacker','impl','done','P2',NULL,NULL,NULL,'plan/details/research/repos/WORK-PACKAGE.md','app/Actions/RunAiConversationCycleAction.php; app/Actions/BuildAuthoredSocialReplyAction.php','On a hostile inbound, send one casual authored line to the attacker, bounded once per distinct attacker, reusing the authored-dialogue protocol. Source: ogame-ninja-scripts.','2026-09-17 13:57:29'),
 (76,'WP-017','Liveness floor under next-due time','impl','done','P2',NULL,NULL,NULL,'plan/details/research/repos/WORK-PACKAGE.md','app/Domain/Scheduling/SessionDecisionService.php; app/Domain/Routine/SessionPlanner.php; config/population.php','Clamp nextDueAt to a configurable max idleness so a long persona-shaped absence cannot trip host inactivity cleanup; keyed off explicit AiProfile identity. Confirm the host purge threshold first or this is YAGNI. Source: ogame-opensource-2-ai.','2026-09-17 14:04:35'),
 (77,'WP-018','Rare no-op idle override + anti-bot threshold self-check','impl','done','P2',NULL,NULL,NULL,'plan/details/research/repos/WORK-PACKAGE.md','app/Domain/Decision/DecisionEngine.php','After scoring, a small seeded, skill-band-aware draw selects DoNothing even when real actions exist (never when fleetsaveEligible/reactionWakeAt set); plus a regression test asserting departures stay under the host anti-bot thresholds. Source: hammermaps-ogamex-ai-players.','2026-09-17 14:10:49'),
 (78,'WP-019','P3 investigate list (phalanx, moonshot, jump gate, ...)','discovery','done','P3',NULL,NULL,NULL,'plan/details/research/repos/WORK-PACKAGE.md','plan/details/research/repos/WORK-PACKAGE.md','Phalanx fleet scan, moonshot, jump-gate transfer, metal-dump research, archetype->character-class affinity, game-phase classification, consultation confidence gate + horizon, solar-satellite energy fallback, defended-raid debris valuation, pre-flight round-trip duration, CRN screen->confirm ladder. Each gated on a confirmed host seam.','2026-09-17 14:13:10'),
 (79,'HL-001','SaveResources capability is dead (declared, scored, never produced)','impl','done','P2','W9-1',NULL,NULL,NULL,'app/Enums/AiCapability.php; app/Enums/AiCandidateActionType.php; app/Domain/Perception/PlayerObservationService.php; app/Actions/ScheduleAiIntentAction.php; app/Domain/Decision/Policies/MinerPolicy.php; app/Domain/Decision/Policies/TraderPolicy.php; app/Domain/Decision/Policies/TurtlePolicy.php','Either publish a real hoard-for-next-step intent and execute it, or delete the SaveResources enum case, the three policy weights and the => null branch. Gate 2/3.','2026-09-17 10:43:19'),
 (80,'HL-002','recovery score term is always 0','impl','done','P2','W9-2',NULL,NULL,NULL,'app/Domain/Decision/UtilityScorer.php; app/Domain/Perception/PerceptionSnapshot.php; app/Infrastructure/Perception/PlayerPerceptionBuilder.php; app/Domain/Perception/PlayerObservationService.php','Publish recovery_factor from an existing signal, or delete RECOVERY_WEIGHT, the recovery term and the recoveryFactor snapshot field. Gate 2.','2026-09-17 10:55:35'),
 (81,'HL-003','attack_permitted is hardcoded true (legality never checked)','impl','done','P2','W9-3',NULL,NULL,NULL,'app/Domain/Perception/PlayerObservationService.php; app/Domain/Decision/CandidateActionFactory.php; app/Domain/Decision/RaidPlanner.php','Compute attack_permitted from the host legality answer at report time, or add a legality check to RaidPlanner::plan(); stop publishing a constant true. Gate 3.','2026-09-17 10:47:52'),
 (82,'HL-004','losingRuns is counted and carried but never consumed','impl','done','P2','W9-4',NULL,NULL,NULL,'app/Infrastructure/Battle/NativeRaidEstimator.php; app/Domain/Raid/RaidEstimate.php; app/Domain/Decision/RaidPlanner.php','Add a losing-run threshold to the profit gate (refuse when a majority of the screen loses), or delete losingRuns from RaidEstimate. Gate 2.','2026-09-17 10:49:54'),
 (83,'DISC-008','Synthesize LLM-usage research into adoptable work items','discovery','done','P2',NULL,NULL,NULL,'plan/details/research/repos/llm-ogame-ai.md; plan/details/specs/llm-full-utilisation.md (S9)','plan/details/research/repos/llm-ogame-ai.md','Distill prompting / context-management / model-choice / cost-control ideas into WP tasks. Only 3 repos genuinely call an LLM (ogame-agi Gemini, DotAgent kimi/llama-3.1, OGame Commander Qwen2.5-VL-72B); all route through OpenAI-compatible endpoints at cheap models, force a closed JSON action vocabulary, feed summarized snapshots (never raw DOM) and fall back to deterministic code on any error. Closed 17 Sep 2026: scored the 16 learnings against shipped S1-S8. 15 already shipped/gated/refused (self-reflection and rolling summaries refused by doctrine: budgets.md forbids periodic reflection and per-event summaries, and the six deterministic trigger signals already carry what materially changed). One real gap found inside a shipped slice, recorded as LLM-010: the SDK exposes cacheReadInputTokens and both parsers subtract it from promptTokens, but the gateway reads promptTokens/completionTokens only and settlement passes a hardcoded 0 into the parameter ResolveAiUsageCostAction already prices, so cached input is uncounted, uncharged and unreported. Synthesis written to plan/details/specs/llm-full-utilisation.md S9 (with the scored-learnings table). No code changed.','2026-09-17 12:25:16'),
 (84,'DISC-009','Synthesize PvE research into adoptable work items','discovery','done','P2',NULL,NULL,NULL,'plan/details/research/repos/pve-concepts.md; plan/details/specs/pve-empire.md','plan/details/research/repos/pve-concepts.md','Distill transferable PvE ideas into the PvE empire spec: AI faction racing the same objective (Travian Natars), phased escalation ladder (EVE Triglavian), influence bar gating the climax + completion-gated rewards (EVE Incursions), succession state machine (Stellaris Marauders/Horde), outcome-scaled difficulty (Stellaris Crises). Closed 17 Sep 2026: scored the 12 transferable structures in pve-concepts.md against pve-empire.md and the Package 7 evidence rule. Adopted: the faction races the same objective via one counter on AiCampaign plus its own declared objective set (ideas 1+2+3 folded into one mechanism; objective order is the ladder, the counter is the influence bar) = PVE-001, deferred to a campaign review record. Deferred with a trigger: the coalition-facing campaign page (progress + both sides losses as write-time counters) = PVE-002, waits on a disclosed coalition. No slice needed for contribution rewards, the published window or per-stronghold difficulty (a stronghold is an ordinary account; a difficulty field would be a second authority over the profile). Refused on gate 2/3: titles/achievements, a near-faction scaling penalty, a damage treadmill. Synthesis written to plan/details/specs/pve-empire.md. No code changed.','2026-09-17 12:25:16'),
 (85,'RP-001','Execute repo plan: alaingilbert-ogame','impl','deferred','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/alaingilbert-ogame.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: no repo-specific work remains - every mechanism is indexed as a shared slice: WP-013 (defenceless signal + section-based confidence), WP-019 (phalanx scan). Pointer only; start those slices.','2026-09-17 12:42:38'),
 (86,'RP-002','Execute repo plan: eracle-ogamebot','impl','done','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/eracle-ogamebot.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: the repo plan verdict is "nothing to adopt, nothing to enhance" (REFUSE-only; see WORK-PACKAGE cross-cutting refusals). No work exists.','2026-09-17 12:42:38'),
 (87,'RP-003','Execute repo plan: halfguru-ogamebot','impl','deferred','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/halfguru-ogamebot.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: no repo-specific work remains - WP-010 (colony slot scoring) is pending; the fleetsave-destination mechanism shipped as WP-004 (done). Pointer only.','2026-09-17 12:42:38'),
 (88,'RP-004','Execute repo plan: hammermaps-ogamex-ai-players','impl','done','P2',NULL,NULL,NULL,'plan/details/research/repos/WORK-PACKAGE.md','plan/details/research/repos/plans/hammermaps-ogamex-ai-players.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: every mechanism is indexed elsewhere (WP-018 rare no-op + anti-bot self-check, WP-019 archetype->character-class affinity). Sole repo-specific residue: document the profile fold (raider->Fleeter, defensive->Turtle, neutral->Casual) in the AiArchetype docblock - doc only, no behaviour, no test.','2026-09-17 18:13:43'),
 (89,'RP-005','Execute repo plan: jaesivsm-pyogame','impl','done','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/jaesivsm-pyogame.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: the only mechanism (debris-field recycling) ships as WP-001 (done); the ENHANCE row (the scan finds the raid debris) needed no code. Nothing repo-specific remains.','2026-09-17 12:42:38'),
 (90,'RP-006','Execute repo plan: janeczkins-xbot','impl','deferred','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/janeczkins-xbot.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: no repo-specific work remains - WP-006 (weak-attack gate), WP-010 (colony abandon), WP-012 (surplus transfer), WP-019 (jump gate); harvest-save shipped as WP-005 (done). Pointer only.','2026-09-17 12:42:38'),
 (91,'RP-007','Execute repo plan: jstar88-ogame-algorithms','impl','done','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/jstar88-ogame-algorithms.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: the repo plan verdict is "nothing to adopt, nothing to enhance" (REFUSE-only; see WORK-PACKAGE cross-cutting refusals). No work exists.','2026-09-17 12:42:38'),
 (92,'RP-008','Execute repo plan: jstar88-opbe','impl','deferred','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/jstar88-opbe.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: lower-tail loot shipped as WP-002 (done); the only remnant is WP-019 (re-ground the defended loot tier on debris doctrine). Pointer only.','2026-09-17 12:42:38'),
 (93,'RP-009','Execute repo plan: klaasvp-trashsim','impl','done','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/klaasvp-trashsim.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: outcome buckets ship as WP-003 (done) and the lower-tail loot as WP-002 (done); both ENHANCE rows are the same slices. Nothing repo-specific remains.','2026-09-17 12:42:38'),
 (94,'RP-010','Execute repo plan: kweimann-cruiser','impl','done','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/kweimann-cruiser.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: expedition debris harvest ships in WP-001 (done) and save-destination ranking in WP-004 (done). Nothing repo-specific remains.','2026-09-17 12:42:38'),
 (95,'RP-011','Execute repo plan: maximalcode-combat-sim','impl','done','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/maximalcode-combat-sim.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: battle-outcome distribution ships as WP-003 (done). Nothing repo-specific remains.','2026-09-17 12:42:38'),
 (96,'RP-012','Execute repo plan: ogame-infinity-web-extension','impl','deferred','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/ogame-infinity-web-extension.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: no repo-specific work remains - WP-009 (expedition composition + rotation) is pending and the defended-raid debris valuation sits in WP-019. Pointer only.','2026-09-17 12:42:38'),
 (97,'RP-013','Execute repo plan: ogame-ninja-scripts','impl','deferred','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/ogame-ninja-scripts.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: no repo-specific work remains - WP-008 (standing defence), WP-012 (surplus transfer), WP-016 (message a new attacker); debris recycling shipped as WP-001 (done). Pointer only.','2026-09-17 12:42:38'),
 (98,'RP-014','Execute repo plan: ogame-opensource-2-ai','impl','deferred','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/ogame-opensource-2-ai.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: no repo-specific work remains - the purge/inactivity mechanism is WP-017 (liveness floor, pending). Pointer only.','2026-09-17 12:42:38'),
 (99,'RP-015','Execute repo plan: ogame-tbot-tbot','impl','deferred','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/ogame-tbot-tbot.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: no repo-specific work remains - WP-006 (probe-only inbound), WP-011 (recall timing), WP-014 (spy origin); harvest-save shipped as WP-005 (done). Pointer only.','2026-09-17 12:42:38'),
 (100,'RP-016','Execute repo plan: patrykstefanski-og-battle-engine','impl','done','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/patrykstefanski-og-battle-engine.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: the repo plan verdict is "nothing to adopt, nothing to enhance" (REFUSE-only; see WORK-PACKAGE cross-cutting refusals). No work exists.','2026-09-17 12:42:38'),
 (101,'RP-017','Execute repo plan: peterradzisz-fleet-optimizer','impl','deferred','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/peterradzisz-fleet-optimizer.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: the survival floor shipped as WP-003 (done); the only remnant is WP-019 (CRN screen->confirm ladder, dead until >=2 launch subsets exist). Pointer only.','2026-09-17 12:42:38'),
 (102,'RP-018','Execute repo plan: piecepapercode-barakis','impl','deferred','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/piecepapercode-barakis.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: no repo-specific work remains - WP-008 (standing defence) and WP-019 (solar-satellite energy fallback). Pointer only.','2026-09-17 12:42:38'),
 (103,'RP-019','Execute repo plan: r4fek-ogame-bot','impl','done','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/r4fek-ogame-bot.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: debris harvest ships as WP-001 (done). Nothing repo-specific remains.','2026-09-17 12:42:38'),
 (104,'RP-020','Execute repo plan: racinmat-phpogamebot','impl','deferred','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/racinmat-phpogamebot.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: no repo-specific work remains - WP-007 (storage-before-build) and WP-014 (probe escalation). Pointer only.','2026-09-17 12:42:38'),
 (105,'RP-021','Execute repo plan: rbardtke-ogamex-combat-sim','impl','deferred','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/rbardtke-ogamex-combat-sim.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: no repo-specific work remains - both mechanisms sit in WP-019 (pre-flight round-trip duration, defended loot tier). Pointer only.','2026-09-17 12:42:38'),
 (106,'RP-022','Execute repo plan: shinigallo-ogame-agi','impl','deferred','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/shinigallo-ogame-agi.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: no repo-specific work remains - both mechanisms sit in WP-019 (game-phase classification, consultation confidence gate + horizon). Pointer only.','2026-09-17 12:42:38'),
 (107,'RP-023','Execute repo plan: trilogi77-ogamebot','impl','deferred','P2',NULL,NULL,NULL,NULL,'plan/details/research/repos/plans/trilogi77-ogamebot.plan.md','Execute this repo''s plan: adopt ADOPT-IDEA/ENHANCE rows that pass gates 1-3, skip REFUSE rows (see WORK-PACKAGE cross-cutting refusals). Shared mechanisms are already tracked as WP-* tasks — only repo-specific items here. Audit 17 Sep 2026: no repo-specific work remains - WP-008..WP-015 and WP-019 x3 carry every mechanism; debris recycling and save destination safety shipped as WP-001/WP-004 (done). Pointer only.','2026-09-17 12:42:38'),
 (108,'LLM-010','S9 — settle the provider cache-read tokens (cost undercount)','impl','done','P2',NULL,NULL,NULL,'specs/llm-full-utilisation.md (S9)','app/Infrastructure/Language/LaravelAiLanguageGateway.php; app/Actions/SettleAiUsageReservationAction.php; app/Models/AiUsageReservation.php; app/Actions/BuildAiPilotReportAction.php; app/Actions/SummarizeAiOperabilityAction.php','DISC-008 output. The SDK Usage exposes cacheReadInputTokens and both parsers subtract it from promptTokens (DeepSeek ParsesTextResponses.php:86; OpenAI :142-148), but LaravelAiLanguageGateway reads promptTokens/completionTokens only and SettleAiUsageReservationAction passes a hardcoded 0 into the cached parameter ResolveAiUsageCostAction already prices. So cached input is invisible: uncounted, never charged at the cached_input rate in config/pricing.php, and no lane reports a cache-hit rate. Carry the value through the existing settle path, store it, count it in the input ceiling (promptTokens + cached), report hits per provider/model. Cache-write tokens stay unplumbed (neither supported provider bills them). Spec: plan/details/specs/llm-full-utilisation.md S9.','2026-09-17 18:11:38'),
 (109,'PVE-001','Campaign momentum: the faction races the same objective (7E instance)','deferred','deferred','P2',NULL,NULL,NULL,'specs/pve-empire.md','app/Models/AiCampaign.php; app/Actions/AdvanceAiCampaignStateAction.php; app/Actions/DeclareAiCampaignObjectiveAction.php','DISC-009 output, research idea 1+2+3 folded. Today an Active campaign resolves only on completion and fails on the deadline; the faction advances nothing, so time is the only opponent. Add one counter on AiCampaign plus the faction''s own declared objective set, advanced by the existing ai:advance-campaigns pass on a published schedule, so the coalition win condition becomes complete the ladder first. Objective ordering (scout -> weaken -> final stronghold) is the escalation ladder and the same counter is the influence bar gating the decisive objective - one number, not two mechanisms. Rewards unchanged (ordinary loot/debris + verified contribution record, paid on completion). Gated by the Package 7 evidence rule: needs a campaign review record naming the gap. Spec: plan/details/specs/pve-empire.md.','2026-09-17 12:24:30'),
 (110,'PVE-002','Coalition campaign page: progress + both sides'' losses (situation log)','deferred','deferred','P3',NULL,NULL,NULL,'specs/pve-empire.md','resources/views/; routes/web.php','DISC-009 output, research idea 9. The spec''s deliverable list includes a module-owned coalition-facing campaign page and none exists (only the operator page at admin/ai). Content is decided by the research: objective progress and both sides'' losses as counters aggregated at write time, matching the review loop cheap-to-read rule. Deferred until a disclosed coalition campaign exists - a page for a coalition that does not exist is speculative UI. Spec: plan/details/specs/pve-empire.md.','2026-09-17 12:24:30'),
 (111,'P7-001','7A scope: ordinary-universe consultation (war declaration + new colony triggers)','deferred','deferred','P2',NULL,NULL,NULL,'plan/WORK-PACKAGES.md (Package 7)','app/Actions/RequestCampaignConsultationAction.php; app/Enums/AiCampaignConsultationTrigger.php; app/Actions/BuildCampaignConsultationBriefAction.php; config/campaign-consultation.php','Package 7A, audited 17 Sep 2026. The consultation machinery is NOT missing: transport, off/observe/advice admission, staff switch, trigger allowlist, cooldown, concurrency cap, daily ceilings, receipts, deterministic validation, profile-bounded ranking nudge, thinking-model routing and read-only tools all ship (6A/6B/6C + S4/S5/S8). Six triggers already fire: FleetLoss, RepeatedSetback, ContestedObjective, CoalitionConflict, NewPhase, RankChange. What is genuinely left: (a) two unbuilt events - worth adding only when a caller exists: war declaration and new colony; (b) the shipped lane is campaign-keyed - RequestCampaignConsultationAction::handle() takes an AiCampaign and BuildCampaignConsultationBriefAction builds from it - so ordinary-universe (non-campaign) advice is a shape change, not a config flag, and needs its own budget, caps and evidence gate. Gate: a review record naming a player-visible gap (Package 7 rule).','2026-09-17 12:43:58'),
 (112,'P7-002','7B: semantic recall only if a held-out review beats native retrieval','deferred','deferred','P3',NULL,NULL,NULL,'plan/WORK-PACKAGES.md (Package 7)','app/Infrastructure/Memory/AgentOsLongTermMemory.php; app/Domain/Memory/LongTermMemorySelector.php; app/Actions/EvaluateAiSocialExchangeAction.php','Package 7B, audited 17 Sep 2026. Gate: a held-out review showing native retrieval misses what exact/entity recall closes. The starting evidence points the other way. The AgentOS recall benchmark (15 Sep 2026, 30 trials, Modules/AI/scripts/e2e-agentos-recall-benchmark.php, runs inside ogamex-app) measured the driver value as SUBSTITUTION, not addition: the +33.3pp required-fact recall IS the eviction of newest facts (newest-kept 1/30 external vs 30/30 native), with the promotion unbounded, and the sole consumer (NativeSocialCognition::outstandingDebtPenalty) is unreachable in production because every real help request answers Counter: insufficient_available_amount. Reference profile also runs no local model, so any embedder is a paid hosted call. Reopen only with a held-out review that shows a miss native retrieval cannot close.','2026-09-17 12:43:58'),
 (113,'P7-003','7C: PsychSim diplomacy experiment (driver integration + consumer)','deferred','deferred','P3',NULL,NULL,NULL,'plan/WORK-PACKAGES.md (Package 7)','','Package 7C, audited 17 Sep 2026. PsychSim appears nowhere in the module (grep of app/, config/, tests/ is empty) and is not one of the four supported drivers (native + FAtiMA/CiF + CBRKit + AgentOS), so this is a driver integration plus a diplomacy consumer - the deepest dependency and the least evidenced of Package 7''s slices. Spec bound: one account and 1-3 relevant counterparts at depth one (depth two needs a recorded measured gain and capacity evidence); it may propose social stance or coalition evidence, never fleets, resources, promises or a replacement player runtime. Gate: Package 6 acceptance + a review record naming the gap.','2026-09-17 12:43:58'),
 (114,'REV-005','Confirm the wave-10 session-cost measurements (W10-1, W10-2)','review','done','P1','W10',NULL,NULL,NULL,'Modules/AI/plan/details/GAP-REGISTER.md','Step 0 of the wave-10 performance work, and the reason neither row below may be implemented yet: reproduce the measurements on the committed build before changing code, with the read-only method recorded in the register (a DB::listen listener plus a debug_backtrace walk around one PlayerPerceptionBuilder::build, and the MySQL profiler for the server-side figure). Confirm or correct each figure: 33 queries per GameMissionFactory::getAllMissions() and 0 for the same static metadata read through a class name; ~297 of ~430 perception queries arriving from FacilityChain.php:129; ~34 PlayerService rebuilds per perception from make($id, true) across 20 module and 30 host sites; session jobs 1-36 s while sibling work kinds measure ~310 ms. Deliverable: a note under plan/details/reviews/ with the reproduced figures, the exact call sites, a verdict per row (confirmed / corrected / withdrawn), and for W10-2 the chosen mechanism plus the write-then-reread callers that were audited. No code change in this row. Corrected expectation from the 17 Sep re-measure: the mission path is 105 of 439 perception queries and 4.6-8.0 s of a 19.7-23.1 s build, not 297 queries. Also confirm the environment caveat before trusting any seconds figure: the same statement measures a 45.8 ms median through raw PDO on the application handle and 2.5 ms through the query builder in the same process, so the query counts are the portable finding and the wall clock is a property of this host.','2026-09-17 13:56:15'),
 (115,'IMPL-043','Host mission catalogue without instantiation (W10-1)','impl','done','P1','W10-1',NULL,NULL,NULL,'app/Factories/GameMissionFactory.php; Modules/AI/app/Domain/Decision/FacilityChain.php','Only after REV-005 confirms W10-1. GameMission::__construct pulls FleetMissionService and MessageService, and both constructors require a PlayerService, so resolving any mission builds a player: 4 queries for metadata that is already static (getTypeId, getRequiredResearch and getRequiredShipMachineNames are all static methods). Split the id-to-class map out of getAllMissions() into getMissionClasses(): array<int, class-string<GameMission>>; make getAllMissions() map that through resolve() so the callers that genuinely need instances keep working unchanged (FleetController plus the three admin label lists); make getMissionById() look the class up and throw a clear error for an unknown id instead of a match fallthrough. The module side is one line: FacilityChain::missionRequiredResearch() iterates the class list and calls $class::getRequiredResearch(). Acceptance: perception queries ~430 to ~130 measured on the grand universe via a restart, session jobs back in the ~300 ms band, host suite and module suite green, Gate 2 review clean. Correction 17 Sep 2026 after re-measuring: the filed figure was wrong. The catalogue is 105 of 439 perception queries and 4.6-8.0 s of a 19.7-23.1 s build (~24-36%), because the perception reaches it 3 times per build, not 9. So this row is necessary but NOT sufficient - closing it leaves ~15 s, and IMPL-045 (module-side) and IMPL-044 (host) carry the rest. Corrected acceptance: perception queries 439 -> ~334.','2026-09-17 18:11:38'),
 (116,'IMPL-044','One player reload per job (W10-2)','impl','done','P2','W10-2',NULL,NULL,NULL,'app/Factories/PlayerServiceFactory.php; app/Services/PlayerService.php','Only after REV-005 confirms W10-2. PlayerServiceFactory::make($id, true) rebuilds a PlayerService on every call (~4 queries each: users, highscores, users_tech, plus PlanetListService planets read) and one perception triggers ~34 rebuilds across 20 module and 30 host forced-reload sites. Smallest mechanism first: memoise a forced reload per generation in PlayerServiceFactory, since AppServiceProvider already flushes the singleton factories before every job (the JobProcessing listener), so a second forced reload inside one job re-reads identical rows. Alternative if the audit finds a write-then-reread caller inside one job: make the PlayerService planet list lazy instead. Risk to settle before choosing, not after: a caller that writes and then relies on a second fresh read in the same job would see stale data. Acceptance: rebuilds per perception ~34 to ~1, perception query count down again, session jobs in the ~300 ms band, host suite and module suite green.','2026-09-17 15:20:42'),
 (117,'IMPL-045','Memoise the mission research map once per worker process (W10-1)','impl','done','P1','W10-1, W10-2',NULL,NULL,NULL,'Modules/AI/app/Domain/Decision/FacilityChain.php; Modules/AI/app/Domain/Perception/PlayerObservationService.php; Modules/AI/app/Domain/Decision/','Shipped and deployed 17 Sep 2026: a static memo on FacilityChain, because the host mission catalogue is static and the read was repeated per chain instance (3 catalogue builds per perception). Measured on the grand universe: mission path 105 -> 39 queries, perception 439 -> 372 queries, suite 854/854 green. The player-graph half of the original row was attempted (drop make($id, true) in the 20 read sites) and reverted: it breaks AiCapabilityPublicationTest, because the factory cache is only fresh per job and a host write inside a test/request must still be visible - refiled as IMPL-046.','2026-09-17 13:46:58'),
 (118,'IMPL-046','Resolve the player once per perception instead of per call site (fresh-preserving, W10-2)','impl','done','P2','W10-2',NULL,NULL,NULL,'Modules/AI/app/Domain/Perception/PlayerObservationService.php; Modules/AI/app/Domain/Decision/','The remaining module-side half of W10-2, after the naive version was tried and reverted: dropping make($id, true) at the 20 read sites broke AiCapabilityPublicationTest, because the factory cache is only fresh per job and a host write inside a request (or a test) must still be visible. The correct mechanism resolves the PlayerService exactly once per perception - after the session advance has already forced a reload and before any module write - and passes that instance down through PlayerObservationService and into the planners it invokes, so the read path reloads once instead of ~20 times without losing write freshness. Acceptance: the same freshness test stays green, perception queries fall from 372 toward ~300, suite green.','2026-09-17 14:43:48'),
 (119,'IMPL-047','Refuse colonising at the planet cap (live colonise-spam fix)','impl','done','P1',NULL,NULL,NULL,NULL,'app/Domain/Decision/QueueableColonyPlanner.php','Live read 17 Sep (ogamex-grand): the old cohort (players 12-21) dispatched 4,763 colonise missions in 48h, ~2,300 of them cancelled at arrival because every account was at its host-derived planet cap (astrophysics). QueueableColonyPlanner::plan() never checked the cap, so every 5s session re-planned a colony the host would refuse. Fix: refuse in plan() when planets->planetCount() >= getMaxPlanetAmount() (both host answers, gate 1). Verified live: players 12/17/20/26 now return null; ColonySpyExecutorTest 13/13.','2026-09-17 18:21:06'),
 (120,'RV-001','Solar satellite answers an energy shortfall the building queue cannot','impl','done','P2','P3 audit (piecepapercode-barakis)',NULL,NULL,'plan/details/specs/reopened-repo-value.md','Modules/AI/app/Domain/Decision/EnergyCapacity.php; Modules/AI/app/Domain/Decision/QueueableBuildingPlanner.php; Modules/AI/app/Domain/Decision/QueueableUnitPlanner.php','EnergyCapacity::pending() keeps only objects BuildingQueueObject::accepts(), so unit-based energy producers are unreachable and a planet in deficit whose affordable capacity buildings are exhausted falls through while its mines run at a fraction of their output. Run the same cheapest-first scan over the production objects the UNIT queue accepts, published as a unit intent. Seam: ObjectService::getGameObjectsWithProduction() with the unit accepts-check. Accept: frozen-clock case where an exhausted-deficit planet offers a solar-satellite intent while a planet that can still afford a plant offers the plant first; a mod-added energy unit needs no module edit. Doc: plan/details/specs/reopened-repo-value.md','2026-09-17 19:00:15'),
 (121,'RV-002','U6 launch subset: counter-select the launch per target and simulate before dispatch','impl','in_progress','P2','W6-4',NULL,'U5,U6','plan/details/specs/reopened-repo-value.md','Modules/AI/app/Domain/Decision/QueueableUnitPlanner.php; Modules/AI/app/Domain/Decision/RaidPlanner.php; Modules/AI/app/Infrastructure/Battle/NativeRaidEstimator.php','W6-4 shipped only the payload-sized cargo half. Production and launch are two decisions: the stock is what the account owns, the launch is the minimum hulls that win against THIS target. Derive the launch subset from the target-reported hull mix and defence using the host rapid-fire properties, simulate that subset once before dispatch, and let fodder ride only when the target can threaten the heavies. Accept: a light-fighter swarm draws cruisers, the same stock shown an undefended farm sends kill ships plus cargo, and a mod-added rapid-fire pair changes the selection with no module edit. Also the prerequisite for RV-007. Doc: plan/details/specs/reopened-repo-value.md','2026-09-17 18:53:49'),
 (122,'RV-003','Measure the defended-raid loot tier against the host own debris and repair values','review','todo','P2','W6-1',NULL,'T7','plan/details/specs/reopened-repo-value.md','Modules/AI/app/Domain/Decision/RaidPlanner.php; Modules/AI/plan/details/reviews/','RaidPlanner::LOOT_TIER_DEFENDED is a fixed 2.0 whose comment says debris subsidises a defended run, while claim RAID-014 decided debris stays out of the single-raid profit gate. One bounded read over existing artifacts (ai_decision_traces score components, ai_action_receipts, the estimator P20 output) asking whether the fixed tier admits a defended run the host debris and defence-repair values do not pay for, and whether it refuses one they do. Deliverable: a dated review record with the before figure and a verdict that either closes this as not-a-defect or points at RV-006. No code change. Doc: plan/details/specs/reopened-repo-value.md','2026-09-17 18:35:19'),
 (123,'RV-004','Mine production percentages as a real lever (throttle under deficit, restore after)','impl','todo','P2','P3 audit (ogame-opensource-2-ai)',NULL,NULL,'plan/details/specs/reopened-repo-value.md','Modules/AI/app/Actions/SetAiMinePercentAction.php; Modules/AI/app/Domain/Decision/EnergyCapacity.php; Modules/AI/app/Domain/Decision/QueueableBuildingPlanner.php','The host lets a planet run each mine at a percentage (planets.*_percent via PlanetService::setBuildingPercent/getBuildingPercent, already exposed to players by ResourcesController) and the module uses neither side. One action and one rule: while the planet is in deficit, lower the mine with the worst output-per-energy to the highest percentage the remaining energy covers; when a capacity building lands, restore it. The object is chosen from host-reported production, never a machine name. Accept: frozen-clock case where exactly one mine is throttled, the host energy balance recovers, a later session restores it, and the receipt records before/after percentages. Doc: plan/details/specs/reopened-repo-value.md','2026-09-17 18:35:19'),
 (124,'RV-005','Confirm an admitted account owns a moon, and record its moon facilities','discovery','todo','P3','precondition gate',NULL,NULL,'plan/details/specs/reopened-repo-value.md','Modules/AI/plan/details/specs/reopened-repo-value.md; Modules/AI/plan/details/reviews/','RV-008 and RV-009 cannot start without an owned moon and none exists today: the whole grand universe holds one moon (planets.planet_type = 3) and it is owned outside the cohort. Read planets for planet_type = 3 among admitted accounts, record which account owns one and which moon facilities it has, or record that none exists yet; a moon arrives through ordinary play (host calculateMoonChance on a fleet crash). Accept: a dated line naming the owner and its facilities, or stating none exists. Doc: plan/details/specs/reopened-repo-value.md','2026-09-17 18:35:19'),
 (125,'RV-006','Ground the defended loot tier in the host own debris and repair values','impl','todo','P2','W6-1',NULL,'T7','plan/details/specs/reopened-repo-value.md','Modules/AI/app/Domain/Decision/RaidPlanner.php','Applies the verdict RV-003 measured: replace the fixed LOOT_TIER_DEFENDED = 2.0 with the tier the host own debris and defence-repair values support, or close this row as not-a-defect if the measurement says the constant is right. No config knob. Accept: the frozen-clock raid tests stay green and a new test fails if a defended run is admitted at a tier the host debris/repair numbers do not cover. Doc: plan/details/specs/reopened-repo-value.md','2026-09-17 18:35:27'),
 (126,'RV-007','CRN screen-then-confirm ladder across launch subsets','impl','todo','P3','P3 audit (peterradzisz-fleet-optimizer)',NULL,NULL,'plan/details/specs/reopened-repo-value.md','Modules/AI/app/Infrastructure/Battle/NativeRaidEstimator.php; Modules/AI/app/Domain/Decision/RaidPlanner.php','One seed stream per candidate so two launch subsets are compared through common random numbers, a cheap screen over all candidates and the wide confirmation spent on the winner. Dead machinery before RV-002, because with fewer than two candidates the ladder has nothing to choose between - that is why it is gated. Accept: two subsets scored through the shared stream rank identically to a single-stream run, and the wide pass runs only on the winner (assert on the sample counter). Doc: plan/details/specs/reopened-repo-value.md','2026-09-17 18:35:27'),
 (127,'RV-008','Sensor phalanx: build it on an owned moon, then scan the target before the raid','impl','todo','P3','P3 audit (alaingilbert-ogame)',NULL,NULL,'plan/details/specs/reopened-repo-value.md','Modules/AI/app/Domain/Decision/QueueablePhalanxPlanner.php; Modules/AI/app/Domain/Decision/FacilityChain.php; Modules/AI/app/Actions/','PhalanxService ships in the host and the module never calls it. A fleeter with a moon scans before committing, and a scan is the only way to see a fleet stationed inside the planet that the espionage report cannot show. The row carries its own prerequisite: build the sensor phalanx on the moon first through the existing building path. Host canScanTarget is the only legality gate and must be respected exactly - an out-of-range scan is a ban risk, not a profit. One candidate source when a phalanx exists and the raid is otherwise viable, folded into the existing observation path. Accept: without a phalanx no scan candidate is published; with one the stationed fleet changes the raid decision; a host-refused scan is recorded and writes no game state. Doc: plan/details/specs/reopened-repo-value.md','2026-09-17 18:35:27'),
 (128,'RV-009','Jump gate: move the fleetsave between own moons instead of flying it','impl','todo','P3','P3 audit (janeczkins-xbot)',NULL,NULL,'plan/details/specs/reopened-repo-value.md','Modules/AI/app/Domain/Decision/QueueableFleetSavePlanner.php; Modules/AI/app/Actions/QueueAiFleetSaveAction.php; Modules/AI/app/Domain/Decision/FacilityChain.php','JumpGateService ships and is unused. With two owned moons a player moves the parked fleet between them instead of flying it - a save that costs no flight time - and the module fleetsave already ranks own bodies. Add the jump-gate move as one more destination kind the existing ranking can pick when it beats a flight, only when the cooldown and both facilities allow; the row carries building the gate as a FacilityChain step. Low value with a single moon: the mechanism is a destination pair. Accept: with one moon nothing changes; with two, a frozen-clock case picks the jump over the flight and a cooldown-blocked one falls back to the flight. Doc: plan/details/specs/reopened-repo-value.md','2026-09-17 18:35:27'),
 (129,'RV-010','Metal-dump research while saving (deferred on a measured case)','deferred','deferred','P3','P3 audit (trilogi77-ogamebot)',NULL,NULL,'plan/details/specs/reopened-repo-value.md','Modules/AI/app/Domain/Decision/FacilityChain.php; Modules/AI/app/Domain/Decision/EconomyUpgrades.php','TRIGGER: a measured metal-capped state that EconomyUpgrades::spendSurplus() and FacilityChain both leave unresolved - metal being discarded with an idle queue. The full-warehouse spend (W8-L4) and the facility chain already cover the ordinary case, and FacilityChain is the module only research source, so building this now is machinery for a value nothing varies on. Doc: plan/details/specs/reopened-repo-value.md','2026-09-17 18:35:34'),
 (130,'RV-011','Game-phase classification (deferred on a named consumer)','deferred','deferred','P3','P3 audit (shinigallo-ogame-agi)',NULL,NULL,'plan/details/specs/reopened-repo-value.md','Modules/AI/app/Domain/Decision/; Modules/AI/plan/details/specs/reopened-repo-value.md','TRIGGER: a named consumer that varies a decision on the phase. The audit cut this for having no host seam, but a phase is derivable from host reads (own rank, object levels, the host highscore distribution) with no host change - so the missing piece is a consumer, not a seam. With none it is config for a value nothing varies on (gate 2). Doc: plan/details/specs/reopened-repo-value.md','2026-09-17 18:35:34'),
 (131,'RV-012','Consultation confidence gate and horizon (deferred on the lane and a signal)','deferred','deferred','P3','P3 audit (shinigallo-ogame-agi)',NULL,NULL,'plan/details/specs/reopened-repo-value.md','Modules/AI/app/Actions/BuildCampaignConsultationBriefAction.php; Modules/AI/app/Actions/ApplyCampaignConsultationRankingAction.php','TRIGGER: the 6A/7A consultation lane enabled AND a confidence source present in the brief. The brief carries no confidence signal today and the lane is off by default, so suppressing a low-confidence nudge has nothing to suppress. Doc: plan/details/specs/reopened-repo-value.md','2026-09-17 18:35:34'),
 (132,'RV-013','Moonshot: sacrificial self-battle to farm debris (cut, not deferred)','deferred','deferred','P3','P3 audit (trilogi77-ogamebot)',NULL,NULL,'plan/details/specs/reopened-repo-value.md','Modules/AI/plan/details/specs/reopened-repo-value.md','CUT, recorded so it is not re-mined. AttackMission::checkOwnPlanet refuses self-attacks by design, so the self-battle seam does not exist; and sending a fleet to die on a neighbour to farm the debris is machine-shaped against gate 3 - no ordinary player does it. Reopens only if the owner asks for the host seam and a named-play justification. Doc: plan/details/specs/reopened-repo-value.md','2026-09-17 18:35:34'),
 (133,'W11-1','Ferry quote spent before dispatch — the transfer loop was refused by the host','impl','done','P1','W11-1',NULL,NULL,NULL,'app/Actions/QueueAiTransferAction.php; app/Domain/Decision/QueueableTransferPlanner.php; app/Enums/AiQueueActionReason.php','Closed 17 Sep 2026. Clamp the shipment to the source''s stock at dispatch, abandon a remnant below MINIMUM_SHIPMENT as source_short_at_dispatch, leave FleetMissionService::calculateConsumption fuel behind. Measured: 617/618 transfers refused in an hour before; 0 host resource refusals and 13 flown in the 90s after. 867 module tests green.','2026-09-17 18:38:02');
-- ── dependencies ─────────────────────────────────────────────────────────────────────────────────────
INSERT OR REPLACE INTO dependencies (task_id, depends_on, reason) VALUES
 (2, 1, 'all impl gated on review'),
 (3, 2, 'raid target score consumes the activity/intel reader'),
 (4, 2, 'spy target score consumes the activity/intel reader'),
 (5, 2, 'proactive save consumes the activity/intel reader'),
 (6, 3, 'fleetcrash after raid depth'),
 (6, 4, 'fleetcrash after intelligence depth'),
 (6, 5, 'fleetcrash after save depth'),
 (7, 1, 'review only; parallel-safe once reviewed'),
 (7, 17, 'needs the U-series block written first'),
 (8, 6, 'ninja timing rides the fleetcrash executors'),
 (8, 18, 'needs the ninja block written first'),
 (9, 1, 'review'),
 (9, 16, 'needs a verified expedition host surface'),
 (9, 19, 'needs the expedition block written first'),
 (11, 20, NULL),
 (20, 1, NULL),
 (28, 27, NULL),
 (32, 31, NULL),
 (33, 48, '6B ships only if the 2/5/10 comparison shows a player-visible gain'),
 (34, 32, NULL),
 (35, 32, NULL),
 (36, 34, NULL),
 (36, 35, NULL),
 (39, 38, 'the algorithm block comes before the code (register rule)'),
 (40, 38, 'the algorithm block comes before the code (register rule)'),
 (41, 38, 'the algorithm block comes before the code (register rule)'),
 (43, 38, 'the algorithm block comes before the code (register rule)'),
 (44, 39, 'the fleet ceiling is the leading hypothesis for the starved reports'),
 (44, 43, 'in-flight probe budgeting feeds the same report flow'),
 (45, 38, 'the algorithm block comes before the code (register rule)'),
 (47, 37, 'the re-read has to be against the committed build'),
 (52, 50, NULL),
 (53, 52, NULL),
 (54, 51, NULL),
 (54, 53, NULL),
 (55, 52, NULL),
 (55, 53, NULL),
 (56, 53, NULL),
 (56, 54, NULL),
 (57, 55, NULL),
 (58, 51, NULL),
 (58, 55, NULL),
 (115, 114, NULL),
 (116, 114, NULL),
 (117, 114, NULL),
 (118, 114, NULL),
 (125, 122, NULL),
 (126, 121, NULL),
 (127, 124, NULL),
 (128, 124, NULL);
